# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.4.1

pipelines:
  default:
    - step:
        script:
          - apt-get update -y
          - apt-get install -y build-essential git-core curl nodejs ssh
          - apt-get clean
          - gem install bundler
          - bundle install

definitions:
  caches:
    bundler: ./vendor