# This is a sample build configuration for Ruby.
# Check our guides at https://confluence.atlassian.com/x/8r-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.5.1
pipelines:
  default:
    - step:
        script:
          - apt-get update -y
          - apt-get install -y build-essential
          - apt-get install -y git-core curl
          - apt-get install -y curl
          - apt-get install -y nodejs
          - apt-get install -y ssh
          - apt-get clean
          - apt-get install zip unzip -y
          - apt-get update -y
          - apt-get install -y unzip openjdk-8-jre-headless xvfb libxi6 libgconf-2-4
          - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
          - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          - apt-get -y update
          - apt-get -y install google-chrome-stable
          - gem install bundler
          - bundle install
          - CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
          - wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
          - unzip ~/chromedriver_linux64.zip -d ~/
          - rm ~/chromedriver_linux64.zip
          - mv -f ~/chromedriver /usr/local/bin/chromedriver
          - chown root:root /usr/local/bin/chromedriver
          - chmod 0755 /usr/local/bin/chromedriver
          - export IS_PIPELINE=true
          - bundle exec rake db:migrate RAILS_ENV=test
          - bundle exec rspec spec
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: test_db
        POSTGRES_USER: test_user
        POSTGRES_PASSWORD: test_user



