development:
  adapter: postgresql
  encoding: unicode
  database: db_dev_ottrtax_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: test_user
  password: test_user
  host: localhost
  port: 5432

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: db_dev_ottrtax_test
#   pool: 5
#   username: postgres
#   password: password
#   host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: db_dev_ottrtax_production
  pool: 5
  username: postgres
  password: password
  host: localhost
