development:
  adapter: postgresql
  encoding: unicode
  database: db_dev_ottrtax_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: db_dev_ottrtax_test
  pool: 5
  username: postgres
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: db_dev_ottrtax_production
  pool: 5
  username: postgres
  password: password
  host: localhost
